### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by sunnyguohua** [liuxx001/bird-front#13]
版本：
[root@localhost bird-front]# node -v
v6.17.1
[root@localhost bird-front]# npm -v
3.10.10
[root@localhost bird-front]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[root@localhost bird-front]#

错误：
/root/bird-front/node_modules/update-notifier/index.js:74
                        (async () => {
                               ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/bird-front/node_modules/umi/lib/cli.js:69:17)

npm ERR! Linux 3.10.0-957.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! bird-front@2.0.0 start: `umi dev --port=8000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bird-front@2.0.0 start script 'umi dev --port=8000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bird-front package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     umi dev --port=8000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bird-front
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bird-front
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/bird-front/npm-debug.log

**Comment by liuxx001** [comment]
@sunnyguohua 换高版本的nodejs试试呢
