### ISSUE TITLE
npm run start 报错

### ISSUE THREAD

**Issue by haishangfeng** [liuxx001/bird-front#9]
ERROR  Failed to compile with 1 errors                                                   2:00:00 PM

This relative module was not found:

* ./LayoutTwo in ./src/layouts/index.js

**Comment by liuxx001** [comment]
@haishangfeng 有更详细的错误信息么？我这里重新克隆，运行是没有问题的。

**Comment by chuiliu** [comment]
登录报错了
```js
The script has an unsupported MIME type ('text/html').
Failed to load resource: net::ERR_INSECURE_RESPONSE
index.js:1 uncaught at _callee3 at _callee3 
 at _callee6 
 at takeEvery(login/login, _callee) 
 at _callee 
 at _callee 
 Error: Error: <!DOCTYPE html><html lang="en"><head>

<link rel="stylesheet" href="/umi.css">

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="A admin dashboard application demo built upon Ant Design and Dva.js">
  <title>bird-front</title>
  <!--[if lte IE 10]>
      <script
        src="https://as.alipayobjects.com/g/component/??console-polyfill/0.2.2/index.js,media-match/2.0.2/media.match.min.js"></script>
  <![endif]-->
<script>
  window.routerBase = "/";
</script>
<script src="/umi.dll.js"></script>
</head>

<body>
  <div id="root"></div>
<script src="/umi.js"></script>



</body></html>
    at onError (http://localhost:8000/umi.dll.js:85765:44)
    at sagaWithCatch$ (http://localhost:8000/umi.dll.js:85322:13)
    at tryCatch (http://localhost:8000/umi.dll.js:3859:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/umi.dll.js:4085:22)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:8000/umi.dll.js:3911:21)
    at next (http://localhost:8000/umi.dll.js:220311:32)
    at Object.currCb [as cont] (http://localhost:8000/umi.dll.js:220410:7)
    at end (http://localhost:8000/umi.dll.js:220378:23)
    at abort (http://localhost:8000/umi.dll.js:220101:5)
    at Object.task.cont (http://localhost:8000/umi.dll.js:220114:9)
    at next (http://localhost:8000/umi.dll.js:220350:16)
    at currCb (http://localhost:8000/umi.dll.js:220410:7)
    at runSelectEffect (http://localhost:8000/umi.dll.js:220721:7)
    at runEffect (http://localhost:8000/umi.dll.js:220457:761)
    at next (http://localhost:8000/umi.dll.js:220337:9)
    at currCb (http://localhost:8000/umi.dll.js:220410:7)
    at http://localhost:8000/umi.dll.js:85772:17
    at http://localhost:8000/umi.dll.js:84796:26
    at onError (http://localhost:8000/umi.dll.js:85773:11)
    at sagaWithCatch$ (http://localhost:8000/umi.dll.js:85322:13)
    at tryCatch (http://localhost:8000/umi.dll.js:3859:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/umi.dll.js:4085:22)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:8000/umi.dll.js:3911:21)
    at next (http://localhost:8000/umi.dll.js:220311:32)
    at Object.currCb [as cont] (http://localhost:8000/umi.dll.js:220410:7)
    at end (http://localhost:8000/umi.dll.js:220378:23)
    at abort (http://localhost:8000/umi.dll.js:220101:5)
    at Object.task.cont (http://localhost:8000/umi.dll.js:220114:9)
    at next (http://localhost:8000/umi.dll.js:220350:16)
    at currCb (http://localhost:8000/umi.dll.js:220410:7)
    at runSelectEffect (http://localhost:8000/umi.dll.js:220721:7)
    at runEffect (http://localhost:8000/umi.dll.js:220457:761)
    at next (http://localhost:8000/umi.dll.js:220337:9)
    at currCb (http://localhost:8000/umi.dll.js:220410:7)
```

**Comment by itlwy** [comment]
git clone https://github.com/liuxx001/bird-front
克隆下来后，npm run start 运行报一样的错：
This relative module was not found:

* ./LayoutTwo in ./src/layouts/index.js

**Comment by liuxx001** [comment]
大小写问题，已修复

**Comment by liuxx001** [comment]
@chuiliu 

账号：admin   密码：admin
用这个账号登录
